# Generated by Django 4.1.5 on 2023-01-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='updated_file',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
