# Generated by Django 4.1.6 on 2023-02-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_galleryuser_delete_userapi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trailingcomments',
            name='parent_comment',
        ),
        migrations.RemoveField(
            model_name='trailingcomments',
            name='trailing_comment',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='user',
        ),
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='TrailingComments',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
