# Generated by Django 4.1.6 on 2023-02-07 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rest_api', '0005_remove_trailingcomments_parent_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(max_length=1200)),
                ('leading_comment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rest_api.comment')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments', to='rest_api.photo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.SmallIntegerField()),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='votes', to='rest_api.photo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrailingComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_comment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='parent_comments', to='rest_api.comment')),
                ('trailing_comment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='trailing_comments', to='rest_api.comment')),
            ],
            options={
                'db_table': 'trailing_comment',
            },
        ),
    ]
