# Generated by Django 4.1.6 on 2023-02-07 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0006_comment_vote_trailingcomment'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='galleryuser',
            table='rest_api_gallery_user',
        ),
        migrations.AlterModelTable(
            name='trailingcomment',
            table='rest_api_trailing_comment',
        ),
    ]
