# Generated by Django 4.1.6 on 2023-02-15 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rest_api", "0007_alter_galleryuser_table_alter_trailingcomment_table"),
    ]

    operations = [
        migrations.RenameField(
            model_name="galleryuser",
            old_name="social_avatar_url",
            new_name="avatar",
        ),
        migrations.RemoveField(
            model_name="galleryuser",
            name="social_access_token",
        ),
        migrations.RemoveField(
            model_name="galleryuser",
            name="social_login_provider",
        ),
        migrations.RemoveField(
            model_name="galleryuser",
            name="social_user_id",
        ),
        migrations.AddField(
            model_name="galleryuser",
            name="about",
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name="galleryuser",
            name="nickname",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
