# Generated by Django 4.1.7 on 2023-02-18 10:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rest_api", "0009_post"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Post",
            new_name="AdminMessage",
        ),
        migrations.AlterModelTable(
            name="adminmessage",
            table="rest_api_admin_message",
        ),
    ]
