# Generated by Django 4.1.7 on 2023-02-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rest_api", "0010_rename_post_adminmessage_alter_adminmessage_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="galleryuser",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
