# Generated by Django 4.1.7 on 2023-02-19 09:03

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rest_api", "0011_alter_galleryuser_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminmessage",
            name="content",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
