# Generated by Django 4.1.7 on 2023-02-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rest_api", "0012_alter_adminmessage_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="galleryuser",
            name="nickname",
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
